name: Publish Quarto

on:
  push:
    branches: main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

      - name: Install Graphviz
        run: |
          sudo apt-get install -y graphviz

      - name: Install PlantUML
        run: |
          sudo apt-get install -y plantuml

      - name: Check PlantUML
        run: |
          java -version
          dot -V
          plantuml -version

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4